"use client";

import { useState } from "react";
import { useAccount } from "wagmi";
import { formatUnits } from "viem";
import { FileText, BarChart2, Download, CheckCircle, CalendarCheck, TrendingUp, Shield } from "lucide-react";
import {
  useVaultBalance, useTotalStaked, useCompany, useEmployees, useMonthlyPayroll,
  fmtUsdc, fmtStt,
} from "@/lib/hooks";

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function nowDate() {
  return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}
function monthLabel() {
  return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" });
}
function quarterLabel() {
  const m = new Date().getMonth();
  const q = Math.floor(m / 3) + 1;
  return `Q${q} ${new Date().getFullYear()}`;
}

export function Analytics() {
  const { address, isConnected } = useAccount();
  const { data: vaultBal }    = useVaultBalance();
  const { data: totalStaked } = useTotalStaked();
  const { data: company }     = useCompany(address);
  const { data: employees }   = useEmployees(address);
  const { data: monthlyTotal } = useMonthlyPayroll(address);

  const [generated, setGenerated] = useState<string | null>(null);

  const companyName  = (company?.name as string | undefined) ?? "Your Company";
  const isRegistered = company?.owner === address;
  const emps         = (employees as { name: string; wallet: string; salaryUsdc: bigint; active: boolean }[] | undefined) ?? [];
  const activeEmps   = emps.filter(e => e.active);
  const monthlyUsd   = monthlyTotal ? Number(formatUnits(monthlyTotal as bigint, 6)) : 0;
  const vaultUsd     = company?.usdcBalance ? Number(formatUnits(company.usdcBalance as bigint, 6)) : 0;
  const runwayMonths = monthlyUsd > 0 ? (vaultUsd / monthlyUsd).toFixed(1) : "—";

  function generateMonthlySummary() {
    const lines = [
      "═══════════════════════════════════════════════════",
      "         LYMITRA — MONTHLY PAYROLL SUMMARY",
      "═══════════════════════════════════════════════════",
      "",
      `Company:       ${companyName}`,
      `Period:        ${monthLabel()}`,
      `Generated:     ${nowDate()}`,
      `Network:       Somnia Shannon Testnet`,
      "",
      "───────────────────────────────────────────────────",
      "  PAYROLL OVERVIEW",
      "───────────────────────────────────────────────────",
      `  Total employees:    ${activeEmps.length}`,
      `  Monthly payroll:    $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `  Vault reserve:      $${vaultUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `  Estimated runway:   ${runwayMonths} months`,
      "",
      "───────────────────────────────────────────────────",
      "  EMPLOYEE BREAKDOWN",
      "───────────────────────────────────────────────────",
      `  ${"Name".padEnd(22)} ${"Wallet".padEnd(14)} Salary (USDC)`,
      `  ${"─".repeat(52)}`,
      ...activeEmps.map(e => {
        const salary = Number(formatUnits(e.salaryUsdc, 6));
        const shortWallet = e.wallet.slice(0, 6) + "…" + e.wallet.slice(-4);
        return `  ${e.name.padEnd(22)} ${shortWallet.padEnd(14)} $${salary.toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
      }),
      `  ${"─".repeat(52)}`,
      `  ${"TOTAL".padEnd(38)} $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
      "",
      "───────────────────────────────────────────────────",
      "  EXECUTION DETAILS",
      "───────────────────────────────────────────────────",
      "  Method:             AI-autonomous · On-chain",
      "  Fee:                1% of payroll disbursed",
      `  Fee amount:         $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      "  Settlement time:    < 1 second (Somnia)",
      "  Audit trail:        Immutable · On-chain forever",
      "",
      "═══════════════════════════════════════════════════",
      "  Generated by Lymitra — lymitra.xyz",
      "═══════════════════════════════════════════════════",
    ];
    downloadText(`lymitra-monthly-summary-${new Date().toISOString().slice(0,7)}.txt`, lines.join("\n"));
    setGenerated("monthly");
  }

  function generateQuarterlyAudit() {
    const lines = [
      "═══════════════════════════════════════════════════",
      "       LYMITRA — QUARTERLY AUDIT REPORT",
      "═══════════════════════════════════════════════════",
      "",
      `Company:       ${companyName}`,
      `Period:        ${quarterLabel()}`,
      `Generated:     ${nowDate()}`,
      `Network:       Somnia Shannon Testnet`,
      "",
      "───────────────────────────────────────────────────",
      "  AUDIT SUMMARY",
      "───────────────────────────────────────────────────",
      `  Active employees:   ${activeEmps.length}`,
      `  Monthly payroll:    $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `  Quarterly payroll:  $${(monthlyUsd * 3).toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC (est.)`,
      `  Quarterly fees:     $${(monthlyUsd * 3 * 0.01).toFixed(2)} USDC (1%)`,
      `  Vault reserve:      $${vaultUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      "",
      "───────────────────────────────────────────────────",
      "  COMPLIANCE & CONTROLS",
      "───────────────────────────────────────────────────",
      "  [✓] All salaries paid to registered wallets only",
      "  [✓] On-chain records immutable — no alteration possible",
      "  [✓] AI conversion executed at market rate (DIA oracle)",
      "  [✓] Non-custodial — funds held in company vault only",
      "  [✓] Agent wallet cannot withdraw or modify employee data",
      "  [✓] Owner wallet required for all structural changes",
      "",
      "───────────────────────────────────────────────────",
      "  EMPLOYEE REGISTER (as of audit date)",
      "───────────────────────────────────────────────────",
      `  ${"Name".padEnd(22)} ${"Wallet".padEnd(14)} Annual (est.)`,
      `  ${"─".repeat(52)}`,
      ...activeEmps.map(e => {
        const monthly = Number(formatUnits(e.salaryUsdc, 6));
        const annual  = (monthly * 12).toLocaleString("en-US", { minimumFractionDigits: 2 });
        const shortWallet = e.wallet.slice(0, 6) + "…" + e.wallet.slice(-4);
        return `  ${e.name.padEnd(22)} ${shortWallet.padEnd(14)} $${annual}`;
      }),
      "",
      "  This report is generated from immutable on-chain data.",
      "  Verify independently at: shannon-explorer.somnia.network",
      "",
      "═══════════════════════════════════════════════════",
      "  Generated by Lymitra — lymitra.xyz",
      "═══════════════════════════════════════════════════",
    ];
    downloadText(`lymitra-quarterly-audit-${quarterLabel().replace(" ", "-")}.txt`, lines.join("\n"));
    setGenerated("quarterly");
  }

  function generateInvoice() {
    const invoiceNo = `LYM-${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, "0")}-${Math.floor(Math.random() * 900 + 100)}`;
    const lines = [
      "═══════════════════════════════════════════════════",
      "           LYMITRA — PAYROLL INVOICE",
      "═══════════════════════════════════════════════════",
      "",
      `Invoice No:    ${invoiceNo}`,
      `Date:          ${nowDate()}`,
      `Period:        ${monthLabel()}`,
      `Billed to:     ${companyName}`,
      "",
      "───────────────────────────────────────────────────",
      "  SERVICES RENDERED",
      "───────────────────────────────────────────────────",
      `  ${"Description".padEnd(34)} Amount`,
      `  ${"─".repeat(44)}`,
      `  ${"Payroll disbursement — " + activeEmps.length + " employees".padEnd(34)} $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `  ${"AI conversion & execution fee (1%)".padEnd(34)} $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      `  ${"─".repeat(44)}`,
      `  ${"TOTAL DUE".padEnd(34)} $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      "",
      "───────────────────────────────────────────────────",
      "  PAYMENT DETAILS",
      "───────────────────────────────────────────────────",
      "  Payment method:     Deducted automatically from vault",
      "  Settlement:         On-chain · Somnia Shannon Testnet",
      "  Currency:           USDC (USD Coin)",
      "",
      "  This invoice is generated from on-chain payroll data.",
      "  All transactions are verifiable on the Somnia explorer.",
      "",
      "═══════════════════════════════════════════════════",
      "  Lymitra · Autonomous On-Chain Payroll",
      "  lymitra.xyz · Powered by Somnia",
      "═══════════════════════════════════════════════════",
    ];
    downloadText(`lymitra-invoice-${invoiceNo}.txt`, lines.join("\n"));
    setGenerated("invoice");
  }

  const reports = [
    {
      id: "monthly",
      Icon: BarChart2,
      color: "#5B7FFF",
      title: "Monthly Summary",
      desc: "Full payroll breakdown — employees, salaries, fees, vault runway. Share with your CFO or accountant.",
      action: generateMonthlySummary,
      tag: monthLabel(),
    },
    {
      id: "quarterly",
      Icon: CalendarCheck,
      color: "#3ED9B8",
      title: "Quarterly Audit",
      desc: "Compliance-ready audit report with employee register, controls checklist, and on-chain verification links.",
      action: generateQuarterlyAudit,
      tag: quarterLabel(),
    },
    {
      id: "invoice",
      Icon: FileText,
      color: "#F3BA2F",
      title: "Payroll Invoice",
      desc: "Itemised invoice for the current period — payroll amount, Lymitra fee, and settlement details.",
      action: generateInvoice,
      tag: "Current period",
    },
  ];

  return (
    <div>
      <div className="sec-hd">
        <div>
          <div className="sec-ht">Analytics</div>
          <div className="sec-hs">Protocol stats · Finance reports · On-chain audit trail</div>
        </div>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, background: "rgba(79,196,144,0.1)", border: "1px solid rgba(79,196,144,0.2)", borderRadius: 100, padding: "4px 10px", fontSize: 11, color: "#4FC490", fontWeight: 600 }}>
          <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#4FC490", animation: "pulse 1.8s ease-in-out infinite", display: "inline-block" }} />
          Live
        </span>
      </div>

      {/* Protocol stats */}
      <div className="ss" style={{ marginBottom: "1.5rem" }}>
        <div className="sc">
          <div className="sc-l">Total vault TVL</div>
          <div className="sc-v accent">{fmtUsdc(vaultBal as bigint | undefined)}</div>
          <div className="sc-s">USDC locked · all companies</div>
        </div>
        <div className="sc">
          <div className="sc-l">Total staked</div>
          <div className="sc-v gold">{fmtStt(totalStaked as bigint | undefined)} SOMI</div>
          <div className="sc-s">protocol-wide</div>
        </div>
        <div className="sc">
          <div className="sc-l">Gas fees</div>
          <div className="sc-v green">~$0.00</div>
          <div className="sc-s">Somnia · near-zero</div>
        </div>
        <div className="sc">
          <div className="sc-l">Network</div>
          <div className="sc-v" style={{ fontSize: 13 }}>Somnia</div>
          <div className="sc-s">Shannon Testnet</div>
        </div>
      </div>

      {/* Finance Hub */}
      <div className="card" style={{ marginBottom: "1.25rem" }}>
        <div className="card-h">
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ width: 28, height: 28, borderRadius: 8, background: "rgba(91,127,255,0.1)", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <Shield size={14} color="var(--accent)" />
            </div>
            <div>
              <div className="card-t">Finance Hub</div>
              <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 1 }}>Generate reports · Export for your accountant or CFO</div>
            </div>
          </div>
          {!isConnected && (
            <span style={{ fontSize: 11, color: "var(--text3)" }}>Connect wallet to generate</span>
          )}
        </div>

        {!isRegistered && isConnected && (
          <div style={{ margin: "0 1.4rem 1.2rem", padding: "0.75rem 1rem", background: "rgba(243,186,47,0.06)", border: "1px solid rgba(243,186,47,0.18)", borderRadius: 8, fontSize: 13, color: "var(--text3)" }}>
            Register your company in the Vault to unlock finance reports.
          </div>
        )}

        <div style={{ padding: "0 1.4rem 1.2rem", display: "flex", flexDirection: "column", gap: 10 }}>
          {reports.map(({ id, Icon, color, title, desc, action, tag }) => (
            <div key={id} style={{
              display: "flex", alignItems: "flex-start", gap: 14, padding: "1rem 1.1rem",
              background: "var(--bg3)", border: "1px solid var(--border)", borderRadius: 12,
              transition: "border-color 0.15s",
            }}>
              <div style={{ width: 36, height: 36, borderRadius: 10, background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 2 }}>
                <Icon size={16} color={color} />
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 4 }}>
                  <span style={{ fontSize: 13.5, fontWeight: 700, color: "var(--text)" }}>{title}</span>
                  <span style={{ fontSize: 9, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase", color, background: `${color}15`, border: `1px solid ${color}30`, borderRadius: 4, padding: "1px 6px" }}>{tag}</span>
                  {generated === id && <CheckCircle size={12} color="#4FC490" />}
                </div>
                <div style={{ fontSize: 12, color: "var(--text3)", lineHeight: 1.5 }}>{desc}</div>
              </div>
              <button
                onClick={isRegistered ? action : undefined}
                disabled={!isRegistered}
                style={{
                  display: "flex", alignItems: "center", gap: 5, flexShrink: 0,
                  padding: "6px 12px", borderRadius: 8, cursor: isRegistered ? "pointer" : "not-allowed",
                  background: isRegistered ? `${color}15` : "var(--bg2)",
                  border: `1px solid ${isRegistered ? color + "40" : "var(--border)"}`,
                  color: isRegistered ? color : "var(--text3)",
                  fontSize: 12, fontWeight: 600, fontFamily: "inherit",
                  opacity: isRegistered ? 1 : 0.5,
                }}
              >
                <Download size={12} />
                Export
              </button>
            </div>
          ))}
        </div>

        {/* What finance teams get */}
        <div style={{ margin: "0 1.4rem 1.2rem", padding: "0.85rem 1rem", background: "rgba(62,217,184,0.05)", border: "1px solid rgba(62,217,184,0.15)", borderRadius: 10 }}>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "#3ED9B8", marginBottom: 8 }}>What your finance team gets</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>
            {[
              { Icon: TrendingUp,    text: "Monthly payroll breakdown per employee" },
              { Icon: CalendarCheck, text: "Quarterly audit — compliance ready" },
              { Icon: FileText,      text: "Invoices for every payroll cycle" },
              { Icon: Shield,        text: "On-chain records — tamper-proof forever" },
            ].map(({ Icon, text }) => (
              <div key={text} style={{ display: "flex", alignItems: "flex-start", gap: 7, fontSize: 11.5, color: "var(--text2)", lineHeight: 1.4 }}>
                <Icon size={11} color="#3ED9B8" style={{ flexShrink: 0, marginTop: 2 }} />
                {text}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Protocol cards */}
      <div className="g2">
        <div className="card">
          <div className="card-h"><div className="card-t">Vault TVL</div></div>
          <div style={{ padding: "1.5rem 1.1rem", textAlign: "center" }}>
            <div style={{ fontSize: 32, fontWeight: 800, color: "var(--accent)", letterSpacing: "-1px" }}>
              {fmtUsdc(vaultBal as bigint | undefined)}
            </div>
            <div style={{ fontSize: 12, color: "var(--text3)", marginTop: 6 }}>
              Total USDC deposited across all registered companies
            </div>
          </div>
          <div style={{ padding: "0 1.1rem 1.1rem" }}>
            <div className="kv"><span className="kk">Token</span><span className="kv-v">USDC</span></div>
            <div className="kv"><span className="kk">Contract</span><span className="kv-v" style={{ fontFamily: "monospace", fontSize: 11 }}>LymitraVault</span></div>
            <div className="kv"><span className="kk">Chain</span><span className="kv-v">Somnia Shannon Testnet</span></div>
          </div>
        </div>

        <div className="card">
          <div className="card-h"><div className="card-t">Staking pool</div></div>
          <div style={{ padding: "1.5rem 1.1rem", textAlign: "center" }}>
            <div style={{ fontSize: 32, fontWeight: 800, color: "#F5C842", letterSpacing: "-1px" }}>
              {fmtStt(totalStaked as bigint | undefined)}
            </div>
            <div style={{ fontSize: 12, color: "var(--text3)", marginTop: 6 }}>
              SOMI staked across all holders earning USDC yield
            </div>
          </div>
          <div style={{ padding: "0 1.1rem 1.1rem" }}>
            <div className="kv"><span className="kk">Token</span><span className="kv-v">SOMI (native)</span></div>
            <div className="kv"><span className="kk">Contract</span><span className="kv-v" style={{ fontFamily: "monospace", fontSize: 11 }}>LymitraStaking</span></div>
            <div className="kv"><span className="kk">Yield source</span><span className="kv-v">Payroll fees (USDC)</span></div>
          </div>
        </div>
      </div>
    </div>
  );
}
