"use client";

import { useState } from "react";
import Image from "next/image";
import { useAccount, useDisconnect } from "wagmi";
import { formatUnits } from "viem";
import { useTheme } from "@/components/ui/ThemeContext";
import { Sun, Moon, Copy, CheckCircle, ExternalLink, FileText, BarChart2, CalendarCheck, Shield, Zap, LogOut, ChevronRight } from "lucide-react";
import {
  useCompany, useEmployees, useMonthlyPayroll, useAgentAddress,
  useLymBalance, usePendingReward,
  fmtUsdc, fmtLym,
} from "@/lib/hooks";

type Panel = "dashboard" | "vault" | "payments" | "earn" | "profile" | "aichat" | "myagent" | "analytics";

interface ProfileProps {
  onNav: (panel: Panel) => void;
  onGoLanding: () => void;
}

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function Profile({ onNav, onGoLanding }: ProfileProps) {
  const { address, isConnected } = useAccount();
  const { disconnect }           = useDisconnect();
  const { theme, toggleTheme }   = useTheme();

  const { data: company }      = useCompany(address);
  const { data: employees }    = useEmployees(address);
  const { data: monthlyTotal } = useMonthlyPayroll(address);
  const { data: agentAddr }    = useAgentAddress();
  const { data: lymBalance }   = useLymBalance(address);
  const { data: pendingReward } = usePendingReward(address);

  const [copied, setCopied] = useState(false);
  const [exported, setExported] = useState<string | null>(null);

  const isRegistered = company?.owner === address;
  const companyName  = (company?.name as string | undefined) ?? "—";
  const empCount     = employees ? (employees as unknown[]).length : 0;
  const monthlyUsd   = monthlyTotal ? Number(formatUnits(monthlyTotal as bigint, 6)) : 0;
  const agentActive  = agentAddr && agentAddr !== "0x0000000000000000000000000000000000000000";
  const emps = (employees as { name: string; wallet: string; salaryUsdc: bigint; active: boolean }[] | undefined) ?? [];
  const activeEmps = emps.filter(e => e.active);

  function copyAddress() {
    if (!address) return;
    navigator.clipboard.writeText(address);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  function nowDate() { return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }); }
  function monthLabel() { return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" }); }
  function quarterLabel() { const q = Math.floor(new Date().getMonth() / 3) + 1; return `Q${q} ${new Date().getFullYear()}`; }

  function generateMonthlySummary() {
    const lines = [
      "═══════════════════════════════════════════════════",
      "         LYMITRA — MONTHLY PAYROLL SUMMARY",
      "═══════════════════════════════════════════════════",
      `Company:       ${companyName}`,
      `Period:        ${monthLabel()}`,
      `Generated:     ${nowDate()}`,
      "",
      `Total employees:  ${activeEmps.length}`,
      `Monthly payroll:  $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `Lymitra fee (1%): $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      "",
      "EMPLOYEE BREAKDOWN",
      "─".repeat(44),
      ...activeEmps.map(e => {
        const salary = Number(formatUnits(e.salaryUsdc, 6));
        const w = e.wallet.slice(0, 6) + "…" + e.wallet.slice(-4);
        return `  ${e.name.padEnd(20)} ${w.padEnd(12)} $${salary.toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
      }),
      "",
      "Generated by Lymitra · lymitra.xyz",
    ];
    downloadText(`lymitra-monthly-${new Date().toISOString().slice(0,7)}.txt`, lines.join("\n"));
    setExported("monthly");
  }

  function generateQuarterlyAudit() {
    const lines = [
      "═══════════════════════════════════════════════════",
      "       LYMITRA — QUARTERLY AUDIT REPORT",
      "═══════════════════════════════════════════════════",
      `Company:       ${companyName}`,
      `Period:        ${quarterLabel()}`,
      `Generated:     ${nowDate()}`,
      "",
      `Active employees:   ${activeEmps.length}`,
      `Monthly payroll:    $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `Quarterly (est.):   $${(monthlyUsd * 3).toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      "",
      "COMPLIANCE",
      "[✓] Salaries paid to registered wallets only",
      "[✓] On-chain records — immutable",
      "[✓] AI conversion at DIA oracle rate",
      "[✓] Non-custodial vault",
      "",
      "Generated by Lymitra · lymitra.xyz",
    ];
    downloadText(`lymitra-audit-${quarterLabel().replace(" ", "-")}.txt`, lines.join("\n"));
    setExported("quarterly");
  }

  function generateInvoice() {
    const inv = `LYM-${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}-${Math.floor(Math.random()*900+100)}`;
    const lines = [
      "═══════════════════════════════════════════════════",
      "           LYMITRA — PAYROLL INVOICE",
      "═══════════════════════════════════════════════════",
      `Invoice No:    ${inv}`,
      `Date:          ${nowDate()}`,
      `Period:        ${monthLabel()}`,
      `Billed to:     ${companyName}`,
      "",
      `Payroll disbursement (${activeEmps.length} employees)   $${monthlyUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })} USDC`,
      `Lymitra fee (1%)                           $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      "",
      `TOTAL DUE: $${(monthlyUsd * 0.01).toFixed(2)} USDC`,
      "",
      "Generated by Lymitra · lymitra.xyz",
    ];
    downloadText(`lymitra-invoice-${inv}.txt`, lines.join("\n"));
    setExported("invoice");
  }

  const initials = address ? address.slice(2, 4).toUpperCase() : "??";

  if (!isConnected) {
    return (
      <div style={{ padding: "3rem 1.5rem", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
        <div style={{ width: 60, height: 60, borderRadius: "50%", background: "var(--accent-dim)", border: "1px solid var(--accent-b)", display: "flex", alignItems: "center", justifyContent: "center" }}>
          <Shield size={24} color="var(--accent)" />
        </div>
        <div>
          <div style={{ fontSize: 17, fontWeight: 700, color: "var(--text)", marginBottom: 6 }}>Connect your wallet</div>
          <div style={{ fontSize: 13, color: "var(--text3)", maxWidth: 240, margin: "0 auto" }}>Connect to see your profile, manage your company, and download reports.</div>
        </div>
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "0.85rem" }}>

      {/* Identity header */}
      <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "1rem 1.1rem", background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 18 }}>
        <div style={{ width: 50, height: 50, borderRadius: "50%", background: "linear-gradient(135deg, #1B3FBF, #4FC4A8)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
          <span style={{ fontSize: 16, fontWeight: 800, color: "#fff" }}>{initials}</span>
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          {isRegistered && (
            <div style={{ fontSize: 15, fontWeight: 700, color: "var(--text)", marginBottom: 2, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{companyName}</div>
          )}
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <span style={{ fontSize: 12, color: "var(--text3)", fontFamily: "monospace" }}>{address?.slice(0, 6)}…{address?.slice(-4)}</span>
            <button onClick={copyAddress} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--text3)", padding: 2, display: "flex" }}>
              {copied ? <CheckCircle size={11} color="#4FC4A8" /> : <Copy size={11} />}
            </button>
            <a href={`https://shannon-explorer.somnia.network/address/${address}`} target="_blank" rel="noopener noreferrer" style={{ color: "var(--text3)", display: "flex" }}>
              <ExternalLink size={11} />
            </a>
          </div>
          {isRegistered && (
            <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 2 }}>
              {empCount} {empCount === 1 ? "employee" : "employees"} · ${monthlyUsd.toLocaleString("en-US", { maximumFractionDigits: 0 })}/mo managed
            </div>
          )}
        </div>
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, flexShrink: 0 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: agentActive ? "#4FC490" : "var(--text3)" }} />
          <span style={{ fontSize: 9, fontWeight: 600, color: "var(--text3)", textTransform: "uppercase", letterSpacing: "0.07em" }}>AI</span>
        </div>
      </div>

      {/* Earnings */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
        <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 14, padding: "0.9rem 1rem" }}>
          <div style={{ fontSize: 19, fontWeight: 800, color: "#4FC4A8", lineHeight: 1 }}>{fmtLym(lymBalance as bigint | undefined)}</div>
          <div style={{ fontSize: 10.5, color: "var(--text3)", marginTop: 4 }}>LYM rewards earned</div>
        </div>
        <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 14, padding: "0.9rem 1rem" }}>
          <div style={{ fontSize: 19, fontWeight: 800, color: "var(--accent)", lineHeight: 1 }}>{fmtUsdc(pendingReward as bigint | undefined)}</div>
          <div style={{ fontSize: 10.5, color: "var(--text3)", marginTop: 4 }}>Staking yield (USDC)</div>
        </div>
      </div>

      {/* Finance Reports */}
      <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 18, overflow: "hidden" }}>
        <div style={{ padding: "0.85rem 1.1rem 0.5rem", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <span style={{ fontSize: 12, fontWeight: 700, color: "var(--text2)" }}>Finance Reports</span>
          {!isRegistered && <span style={{ fontSize: 10.5, color: "var(--text3)" }}>Register a company to export</span>}
        </div>
        {[
          { id: "monthly",   Icon: BarChart2,     color: "#5B7FFF", label: "Monthly Summary",  sub: monthLabel(),     action: generateMonthlySummary },
          { id: "quarterly", Icon: CalendarCheck, color: "#3ED9B8", label: "Quarterly Audit",  sub: quarterLabel(),   action: generateQuarterlyAudit },
          { id: "invoice",   Icon: FileText,      color: "#F3BA2F", label: "Invoice",          sub: "Current period", action: generateInvoice },
        ].map(({ id, Icon, color, label, sub, action }, i, arr) => (
          <button
            key={id}
            onClick={isRegistered ? action : undefined}
            disabled={!isRegistered}
            style={{
              width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "0.8rem 1.1rem",
              background: "none", border: "none",
              borderBottom: i < arr.length - 1 ? "1px solid var(--border)" : "none",
              cursor: isRegistered ? "pointer" : "default", opacity: isRegistered ? 1 : 0.4,
              fontFamily: "inherit", textAlign: "left",
            }}
          >
            <div style={{ width: 34, height: 34, borderRadius: 10, background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
              <Icon size={15} color={color} />
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13.5, fontWeight: 600, color: "var(--text)" }}>{label}</div>
              <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 1 }}>{sub}</div>
            </div>
            {exported === id ? <CheckCircle size={14} color="#4FC490" /> : <ChevronRight size={14} color="var(--text3)" />}
          </button>
        ))}
      </div>

      {/* Navigate */}
      <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 18, overflow: "hidden" }}>
        {[
          { Icon: Zap,    color: "#9B7FFF", label: "My Agent",  sub: "AI payroll automation",   nav: "myagent"   as Panel },
          { Icon: Shield, color: "#3ED9B8", label: "Analytics", sub: "On-chain history & stats", nav: "analytics" as Panel },
        ].map(({ Icon, color, label, sub, nav }, i) => (
          <button
            key={nav}
            onClick={() => onNav(nav)}
            style={{
              width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "0.85rem 1.1rem",
              background: "none", border: "none",
              borderBottom: i === 0 ? "1px solid var(--border)" : "none",
              cursor: "pointer", fontFamily: "inherit", textAlign: "left",
            }}
          >
            <div style={{ width: 34, height: 34, borderRadius: 10, background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
              <Icon size={15} color={color} />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 13.5, fontWeight: 600, color: "var(--text)" }}>{label}</div>
              <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 1 }}>{sub}</div>
            </div>
            <ChevronRight size={14} color="var(--text3)" />
          </button>
        ))}
      </div>

      {/* Settings */}
      <div style={{ background: "var(--bg2)", border: "1px solid var(--border)", borderRadius: 18, overflow: "hidden" }}>
        <button onClick={toggleTheme} style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "0.85rem 1.1rem", background: "none", border: "none", borderBottom: "1px solid var(--border)", cursor: "pointer", fontFamily: "inherit" }}>
          <div style={{ width: 34, height: 34, borderRadius: 10, background: "var(--bg3)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
            {theme === "dark" ? <Sun size={15} color="var(--text2)" /> : <Moon size={15} color="var(--text2)" />}
          </div>
          <div style={{ flex: 1, textAlign: "left", fontSize: 13.5, fontWeight: 600, color: "var(--text)" }}>
            {theme === "dark" ? "Light mode" : "Dark mode"}
          </div>
          <ChevronRight size={14} color="var(--text3)" />
        </button>
        <button onClick={onGoLanding} style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "0.85rem 1.1rem", background: "none", border: "none", borderBottom: "1px solid var(--border)", cursor: "pointer", fontFamily: "inherit" }}>
          <div style={{ width: 34, height: 34, borderRadius: 10, background: "var(--bg3)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
            <ExternalLink size={15} color="var(--text2)" />
          </div>
          <div style={{ flex: 1, textAlign: "left", fontSize: 13.5, fontWeight: 600, color: "var(--text)" }}>Visit website</div>
          <ChevronRight size={14} color="var(--text3)" />
        </button>
        <button onClick={() => disconnect()} style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "0.85rem 1.1rem", background: "none", border: "none", cursor: "pointer", fontFamily: "inherit" }}>
          <div style={{ width: 34, height: 34, borderRadius: 10, background: "rgba(212,115,106,0.12)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
            <LogOut size={15} color="var(--red)" />
          </div>
          <div style={{ flex: 1, textAlign: "left", fontSize: 13.5, fontWeight: 600, color: "var(--red)" }}>Disconnect</div>
        </button>
      </div>

      <div style={{ textAlign: "center", fontSize: 10.5, color: "var(--text3)", paddingBottom: "0.25rem" }}>
        Lymitra · Somnia Shannon Testnet · v1.0
      </div>
    </div>
  );
}
